name: "Release"

on:
  push:
    tags:
      - "v*"

jobs:
  tagged-release:
    name: "deb-package"
    runs-on: "ubuntu-latest"

    permissions:
      security-events: read
      actions: write
      contents: write

    steps:
      - uses: actions/checkout@v4

      - name: setup-env
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential dpkg-dev debhelper fakeroot

      - name: build
        run: |
          cd reverse-tunneld
          chmod 755 DEBIAN/postinst DEBIAN/prerm || true
          chmod 644 DEBIAN/control
          dpkg-deb --build --root-owner-group . ../reverse-tunneld.deb
        working-directory: "."

      - name: create release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          tag: ${{ github.ref_name }}
        run: |
          gh release create "$tag" \
              --title="$tag" \
              --generate-notes

      - name: upload assets
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          tag: ${{ github.ref_name }}
        run: |
          gh release upload "$tag" reverse-tunneld.deb
        working-directory: "."
